#!/bin/bash

version=0.3.1


curdir=$(pwd)
path=$(readlink -f "$0")
dir=$(dirname "$path")

usage()
{
    echo "TODO: Write usage info!"

}


if   [ "$1" == "test" ]; then
    $dir/src/test.sh # TODO
    
elif   [ "$1" == "init" ]; then
    export curdir=$curdir
    envsubst < $dir/config/config.yaml > $curdir/config.yaml
    Rscript $dir/workflow/scripts/init_sample_table.R $2

elif   [ "$1" == "recon" ]; then
    shift
    snakemake -s $dir/workflow/rules/recon.smk "$@" --use-conda --rerun-triggers mtime --scheduler greedy --rerun-incomplete
    
else
    usage
fi
