#!/bin/bash

version=0.1.1


curdir=$(pwd)
path=$(readlink -f "$0")
dir=$(dirname "$path")

usage()
{
    echo "TODO: Write usage info!"

}


if   [ "$1" == "test" ]; then
    $dir/src/test.sh # TODO
    
elif   [ "$1" == "init" ]; then
    cp $dir/config/config.yaml $curdir/config.yaml
    Rscript $dir/workflow/scripts/init_sample_table.R $2

elif   [ "$1" == "recon" ]; then
    shift
    snakemake -s $dir/workflow/rules/recon.smk "$@" --cores 16 --use-conda
    
else
    usage
fi
