
#--------------------------#
# Parameters "gapseq find" #
#--------------------------#
find_threads: 2
find_mem: 1 # Gb
find_time: 10 # hours
find_b: 200 # bitscore cutoff

#------------------------------------#
# Parameters "gapseq find-transport" #
#------------------------------------#
transport_threads: 1
transport_mem: 2 # Gb
transport_time: 1 # hours

#---------------------------#
# Parameter "gapseq draft"  #
#---------------------------#
draft_threads: 1
draft_mem: 1 # Gb
draft_time: 1 # hours

#---------------------------#
# Parameter "gapseq medium" #
#---------------------------#
medium_c: "cpd00007:0"

#---------------------------#
# Parameter "gapseq fill"   #
#---------------------------#
fill_threads: 2
fill_mem: 2 # Gb
fill_b: 100
fill_time: 1 # hours

